services:
  service_a:
    build:
      context: ./services
      dockerfile: Dockerfile_a
    ports:
      - 3001:3001
    environment:
      - target_url=http://service_b:3002
  
  service_b:
    build:
      context: ./services
      dockerfile: Dockerfile_b
    ports:
      - 3002:3002

  prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - "./prometheus/:/etc/prometheus/"

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana-oss:8.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning